---
- include: mysql.yml
  tags: rundeck-mysql

- include: nginx.yml
  tags: rundeck-nginx

- name: Add rundeck repository
  apt_repository:
    repo: 'deb https://rundeck.bintray.com/rundeck-deb /'
    state: present
    filename: rundeck

- name: Install Rundeck Server and cli
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - rundeck={{ rundeck_version }}*
    - rundeck-cli

- name: remove upstart scripts
  file:
    path: /etc/init/rundeckd.conf
    state: absent

- name: Download plugins
  get_url:
    url: "{{ item }}"
    dest: "/var/lib/rundeck/libext/{{ item.split('/')[-1] }}"
    mode: 0644
  with_items: "{{ rundeck_plugins }}"
  notify: restart rundeckd

- name: remove plugins
  file:
    path: "/var/lib/rundeck/libext/{{ item |d(omit) }}"
    state: absent
  with_items: "{{ rundeck_plugins_removed }}"
  notify: restart rundeckd

- name: modify config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - framework.properties
    - rundeck-config.properties
    - log4j.properties
  notify: restart rundeckd
  tags:
    - rundeck-login-module
    - rundeck-properties

- name: Add login module config
  template:
    src: "jaas-{{ rd_login_module }}.conf.j2"
    dest: "/etc/rundeck/jaas-{{ rd_login_module }}.conf"
    owner: rundeck
    group: rundeck
    mode: 0640
  notify: restart rundeckd
  when: rd_login_module is defined
  tags:
    - rundeck-login-module

- name: export login module config
  template:
    src: "rundeckd.j2"
    dest: "/etc/default/rundeckd"
    owner: rundeck
    group: rundeck
    mode: 0640
  notify: restart rundeckd
  when: rd_login_module is defined
  tags:
    - rundeck-login-module

- name: modify config that not require restart
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - admin.aclpolicy
    - rundeckadmin.aclpolicy
    - apitoken.aclpolicy
  tags:
    - rundeck-aclpolicy

- name: put limits.d file
  template:
    src: limits.conf
    dest: /etc/security/limits.d
    owner: root
    group: root
    mode: 0644

- name: modify directory permission
  file:
    path: /etc/rundeck
    state: directory
    owner: rundeck
    group: rundeck
    recurse: yes

- name: modify directory permission
  file:
    path: /var/lib/rundeck
    state: directory
    owner: rundeck

- include: overrides.yml
  when: rundeck_overrides | length > 0
  notify: restart rundeckd
  tags: rundeck-overrides

- name: rundeckd is enabled
  service:
    name: rundeckd
    state: started
    enabled: yes
    sleep: 30

- include: projects.yml
  tags: rundeck-projects    
