- include: mysql.yml
- include: nginx.yml

- name: modify repository
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    state: present

- name: install
  apt:
    name: "rundeck={{ rundeck_version }}*"
    state: present
    force: yes

- name: download plugins
  get_url:
    url: "{{ item }}"
    dest: "/var/lib/rundeck/libext/{{ item.split('/')[-1] }}"
    mode: 0644
  with_items: rundeck_plugins
  notify: restart rundeckd

- name: modify config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - profile
    - framework.properties
    - rundeck-config.groovy
    - realm.properties
    - jaas-loginmodule.conf
    - log4j.properties
  notify: restart rundeckd

- name: modify default policies
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rundeck/{{ item }}"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items:
    - admin.aclpolicy
    - RundeckAdmin.aclpolicy

- name: modify name of default user role
  replace:
    dest: /var/lib/rundeck/exp/webapp/WEB-INF/web.xml
    regexp: "<role-name>user</role-name>"
    replace: "<role-name>{{ rd_default_group_name }}</role-name>"
    backup: yes
  when: rd_default_group_name is defined
  notify: restart rundeckd

- name: modify directory permission
  file:
    path: /etc/rundeck
    state: directory
    owner: rundeck
    group: rundeck
    recurse: yes

- name: rundeckd is enabled
  service:
    name: rundeckd
    state: started
    enabled: yes
