---
- name: Create overrides dir
  file:
    name: "{{ rundeck_overrides_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Overriding binaries
  copy:
    content: |
      #!/bin/bash
      echo "{{ item.msg }}"
      sleep "{{ item.sleep |d(1) }}"
      exit "{{ item.exit |d(1) }}"
    dest: "{{ rundeck_overrides_dir }}/{{ item.bin }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ rundeck_overrides }}"