---

- name: Run rd create project if project directory not exists in file system
  command: "/usr/bin/rd projects create -p {{item}} --file /etc/rundeck/{{ item }}.properties"
  args:
    chdir: /var/rundeck/
    creates: "/var/rundeck/projects/{{item}}"
  environment:
    RD_URL : "http://localhost:4440"
    RD_USER: "{{ framework_server_username }}"
    RD_PASSWORD: "{{ framework_server_password }}"
  with_items: "{{ rd_create_projects }}"
  ignore_errors: true

- name: Create acl for projects
  template:
    src: project.aclpolicy.j2
    dest: "/etc/rundeck/{{ item }}.aclpolicy"
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items: "{{ rd_create_projects }}"

- name: creating base directory for projects
  file:
    name: "/var/rundeck/projects/{{item}}"
    state: directory
    owner: rundeck
    group: rundeck
    mode: '0775'
  with_items: "{{ rd_create_projects }}"